#!/usr/bin/env bash

REQUEST="
CREATE DATABASE username CHARACTER SET UTF8 COLLATE UTF8_BIN;
CREATE USER 'username'@'%' IDENTIFIED BY 'motDePasseSecure';
GRANT ALL PRIVILEGES ON username.* TO 'username'@'%';
FLUSH PRIVILEGES;
"

mysql --user=root <<EOFMYSQL
$REQUEST
EOFMYSQL


exit 0



#####test
#REQUEST="
#CREATE DATABASE te1 CHARACTER SET UTF8 COLLATE UTF8_BIN;
#CREATE DATABASE te2 CHARACTER SET UTF8 COLLATE UTF8_BIN;
#"

#mysql --user=root <<EOFMYSQL
#$REQUEST
#EOFMYSQL

#exit 0